version: "3.7"
services:
  mqttbroker:
    container_name: mqttbroker-mtls
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    hostname: mqttbroker
    network_mode: host
    restart: unless-stopped

