version: "3.7"
services:
  mqttbroker:
    container_name: mqttbroker-mtls
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    hostname: mqttbroker
    network_mode: host
    restart: unless-stopped
  publisher:
    container_name: publisher-mtls
    build: 
      context: .
      dockerfile: dockerfiles/publisher.Dockerfile
    restart: unless-stopped
  subscriber:
    container_name: subscriber-mtls
    build: 
      context: .
      dockerfile: dockerfiles/subscriber.Dockerfile
    restart: unless-stopped

